// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKOADNxwdn-vO0o0xK4M7E9pm0r2ckFsY',
    appId: '1:409683162231:web:4e7b9c996bafc2e066c272',
    messagingSenderId: '409683162231',
    projectId: 'travido-48bc0',
    authDomain: 'travido-48bc0.firebaseapp.com',
    storageBucket: 'travido-48bc0.appspot.com',
    measurementId: 'G-G7M0P5TDMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmT7EZj0uFJgTktXypWemL58NOIghKkDI',
    appId: '1:409683162231:android:890e8825b6cbb8d066c272',
    messagingSenderId: '409683162231',
    projectId: 'travido-48bc0',
    storageBucket: 'travido-48bc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7b4-O32lcnAszea8UXYdgtiNjbVhTews',
    appId: '1:409683162231:ios:aac9503956293ce266c272',
    messagingSenderId: '409683162231',
    projectId: 'travido-48bc0',
    storageBucket: 'travido-48bc0.appspot.com',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7b4-O32lcnAszea8UXYdgtiNjbVhTews',
    appId: '1:409683162231:ios:aac9503956293ce266c272',
    messagingSenderId: '409683162231',
    projectId: 'travido-48bc0',
    storageBucket: 'travido-48bc0.appspot.com',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKOADNxwdn-vO0o0xK4M7E9pm0r2ckFsY',
    appId: '1:409683162231:web:436b18a61adffed166c272',
    messagingSenderId: '409683162231',
    projectId: 'travido-48bc0',
    authDomain: 'travido-48bc0.firebaseapp.com',
    storageBucket: 'travido-48bc0.appspot.com',
    measurementId: 'G-HLEVLY0HBG',
  );
}
